CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name VARCHAR(80) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE pets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL REFERENCES users(id),
    name VARCHAR(80) NOT NULL,
    species VARCHAR(80) NOT NULL,
    breed VARCHAR(80),
    gender VARCHAR(16) NOT NULL CHECK (gender IN ('MALE', 'FEMALE', 'UNKNOWN')),
    birthday DATE,
    bio VARCHAR(500),
    avatar_url VARCHAR(2048),
    private_profile BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX pets_owner_id_idx ON pets(owner_id);

CREATE TABLE communities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    description VARCHAR(500),
    rules VARCHAR(2000),
    created_by_pet_id BIGINT NOT NULL REFERENCES pets(id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX communities_name_unique_idx ON communities (LOWER(name));
CREATE INDEX communities_search_idx ON communities USING GIN (
    to_tsvector('english', name || ' ' || COALESCE(description, '') || ' ' || COALESCE(rules, ''))
);

CREATE TABLE community_members (
    community_id BIGINT NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    pet_id BIGINT NOT NULL REFERENCES pets(id) ON DELETE CASCADE,
    role VARCHAR(16) NOT NULL DEFAULT 'MEMBER' CHECK (role IN ('OWNER', 'MODERATOR', 'MEMBER')),
    joined_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (community_id, pet_id)
);

CREATE INDEX community_members_pet_idx ON community_members(pet_id, community_id);

CREATE TABLE posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id BIGINT NOT NULL REFERENCES pets(id),
    body VARCHAR(2000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX posts_created_at_id_idx ON posts(created_at DESC, id DESC);
CREATE INDEX posts_pet_created_at_id_idx ON posts(pet_id, created_at DESC, id DESC);

CREATE TABLE post_communities (
    post_id BIGINT PRIMARY KEY REFERENCES posts(id) ON DELETE CASCADE,
    community_id BIGINT NOT NULL REFERENCES communities(id)
);

CREATE INDEX post_communities_feed_idx ON post_communities(community_id, post_id);

CREATE TABLE post_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    url VARCHAR(2048) NOT NULL,
    sort_order INTEGER NOT NULL,
    UNIQUE (post_id, sort_order)
);

CREATE TABLE likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    pet_id BIGINT NOT NULL REFERENCES pets(id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (post_id, pet_id)
);

CREATE TABLE comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    pet_id BIGINT NOT NULL REFERENCES pets(id),
    body VARCHAR(500) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX comments_post_created_at_id_idx ON comments(post_id, created_at, id);

CREATE TABLE pet_follows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_pet_id BIGINT NOT NULL REFERENCES pets(id) ON DELETE CASCADE,
    following_pet_id BIGINT NOT NULL REFERENCES pets(id) ON DELETE CASCADE,
    accepted BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pet_follows_distinct_pets CHECK (follower_pet_id <> following_pet_id),
    CONSTRAINT pet_follows_unique_pair UNIQUE (follower_pet_id, following_pet_id)
);

CREATE INDEX pet_follows_following_idx ON pet_follows(following_pet_id, accepted, created_at DESC, id DESC);
CREATE INDEX pet_follows_follower_idx ON pet_follows(follower_pet_id, accepted, created_at DESC, id DESC);

CREATE TABLE pet_blocks (
    blocker_pet_id BIGINT NOT NULL REFERENCES pets(id) ON DELETE CASCADE,
    blocked_pet_id BIGINT NOT NULL REFERENCES pets(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (blocker_pet_id, blocked_pet_id),
    CONSTRAINT pet_blocks_distinct_pets CHECK (blocker_pet_id <> blocked_pet_id)
);

CREATE INDEX pet_blocks_blocked_idx ON pet_blocks(blocked_pet_id, blocker_pet_id);

CREATE TABLE pet_mutes (
    muter_pet_id BIGINT NOT NULL REFERENCES pets(id) ON DELETE CASCADE,
    muted_pet_id BIGINT NOT NULL REFERENCES pets(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (muter_pet_id, muted_pet_id),
    CONSTRAINT pet_mutes_distinct_pets CHECK (muter_pet_id <> muted_pet_id)
);

CREATE TABLE walks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id BIGINT NOT NULL REFERENCES pets(id),
    client_walk_id UUID NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ended_at TIMESTAMP WITH TIME ZONE NOT NULL,
    route geometry(LineString, 4326) NOT NULL CHECK (NOT ST_IsEmpty(route)),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT walks_valid_time CHECK (ended_at >= started_at),
    CONSTRAINT walks_pet_client_id_unique UNIQUE (pet_id, client_walk_id)
);

CREATE INDEX walks_pet_started_idx ON walks(pet_id, started_at DESC, id DESC);
CREATE INDEX walks_route_geography_idx ON walks USING GIST ((route::geography));

CREATE TABLE walk_points (
    walk_id BIGINT NOT NULL REFERENCES walks(id) ON DELETE CASCADE,
    sequence_number INTEGER NOT NULL CHECK (sequence_number >= 0),
    latitude DOUBLE PRECISION NOT NULL CHECK (latitude BETWEEN -90 AND 90),
    longitude DOUBLE PRECISION NOT NULL CHECK (longitude BETWEEN -180 AND 180),
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (walk_id, sequence_number)
);

CREATE TABLE territories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    walk_id BIGINT NOT NULL UNIQUE REFERENCES walks(id) ON DELETE CASCADE,
    area geometry(Polygon, 4326) NOT NULL,
    base_strength INTEGER NOT NULL CHECK (base_strength BETWEEN 1 AND 5),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT territories_valid_area CHECK (ST_IsValid(area) AND NOT ST_IsEmpty(area))
);

CREATE INDEX territories_area_idx ON territories USING GIST (area);
CREATE INDEX territories_created_idx ON territories(created_at DESC, id DESC);

CREATE VIEW territory_ownership AS
SELECT t.id, t.walk_id, w.pet_id, t.area, t.base_strength, current_strength.value AS effective_strength,
       t.created_at,
       ST_Multi(ST_CollectionExtract(ST_Difference(t.area, COALESCE((
           SELECT ST_Union(h.area) FROM territories h
           CROSS JOIN LATERAL (SELECT GREATEST(0, h.base_strength - GREATEST(0,
               FLOOR(EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP - h.created_at)) / 604800)::INTEGER))
               AS value) higher_strength
           WHERE h.id <> t.id AND ST_Intersects(h.area, t.area)
             AND (higher_strength.value > current_strength.value
               OR (higher_strength.value = current_strength.value
                 AND (h.created_at, h.id) > (t.created_at, t.id)))
       ), ST_GeomFromText('POLYGON EMPTY', 4326))), 3)) AS owned_area,
       ST_Area(ST_Intersection(t.area, COALESCE((
           SELECT ST_Union(other.area) FROM territories other
           JOIN walks other_walk ON other_walk.id = other.walk_id
           WHERE other_walk.pet_id <> w.pet_id AND ST_Intersects(other.area, t.area)
       ), ST_GeomFromText('POLYGON EMPTY', 4326)))::geography) AS contested_area_square_meters
FROM territories t JOIN walks w ON w.id = t.walk_id
CROSS JOIN LATERAL (SELECT GREATEST(0, t.base_strength - GREATEST(0,
    FLOOR(EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP - t.created_at)) / 604800)::INTEGER)) AS value)
    current_strength;

CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator_pet_id BIGINT NOT NULL REFERENCES pets(id),
    title VARCHAR(120) NOT NULL,
    description VARCHAR(2000) NOT NULL,
    category VARCHAR(24) NOT NULL CHECK (category IN ('DOG_WALKING', 'PET_SITTING', 'FEEDING', 'CHECK_IN')),
    latitude DOUBLE PRECISION NOT NULL CHECK (latitude BETWEEN -90 AND 90),
    longitude DOUBLE PRECISION NOT NULL CHECK (longitude BETWEEN -180 AND 180),
    location geography(Point, 4326) GENERATED ALWAYS AS
        (ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography) STORED,
    public_location geography(Point, 4326) GENERATED ALWAYS AS
        (ST_SetSRID(ST_MakePoint(ROUND(longitude::numeric, 2)::double precision,
            ROUND(latitude::numeric, 2)::double precision), 4326)::geography) STORED,
    status VARCHAR(16) NOT NULL DEFAULT 'OPEN'
        CHECK (status IN ('OPEN', 'ACCEPTED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX tasks_browse_idx ON tasks(status, created_at DESC, id DESC);
CREATE INDEX tasks_creator_idx ON tasks(creator_pet_id, created_at DESC, id DESC);
CREATE INDEX tasks_location_idx ON tasks USING GIST (location);
CREATE INDEX tasks_public_location_idx ON tasks USING GIST (public_location);

CREATE TABLE task_assignments (
    task_id BIGINT PRIMARY KEY REFERENCES tasks(id) ON DELETE CASCADE,
    pet_id BIGINT NOT NULL REFERENCES pets(id),
    accepted_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX task_assignments_pet_idx ON task_assignments(pet_id, accepted_at DESC);

CREATE TABLE task_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
    actor_pet_id BIGINT NOT NULL REFERENCES pets(id),
    status VARCHAR(16) NOT NULL CHECK (status IN ('OPEN', 'ACCEPTED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX task_events_history_idx ON task_events(task_id, created_at, id);

CREATE TABLE task_ratings (
    task_id BIGINT PRIMARY KEY REFERENCES task_assignments(task_id) ON DELETE CASCADE,
    score INTEGER NOT NULL CHECK (score BETWEEN 1 AND 5),
    comment VARCHAR(500),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE task_availability (
    pet_id BIGINT PRIMARY KEY REFERENCES pets(id) ON DELETE CASCADE,
    accepting_tasks BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_pet_id BIGINT NOT NULL REFERENCES pets(id),
    second_pet_id BIGINT NOT NULL REFERENCES pets(id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (first_pet_id < second_pet_id),
    UNIQUE (first_pet_id, second_pet_id)
);

CREATE INDEX conversations_updated_idx ON conversations(updated_at DESC, id DESC);

CREATE TABLE conversation_members (
    conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    pet_id BIGINT NOT NULL REFERENCES pets(id),
    PRIMARY KEY (conversation_id, pet_id)
);

CREATE INDEX conversation_members_pet_idx ON conversation_members(pet_id, conversation_id);

CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    sender_pet_id BIGINT NOT NULL,
    client_message_id UUID NOT NULL,
    body VARCHAR(2000) NOT NULL CHECK (length(trim(body)) > 0),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (conversation_id, sender_pet_id) REFERENCES conversation_members(conversation_id, pet_id),
    UNIQUE (conversation_id, sender_pet_id, client_message_id)
);

CREATE INDEX messages_conversation_id_idx ON messages(conversation_id, id DESC);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_pet_id BIGINT NOT NULL REFERENCES pets(id),
    actor_pet_id BIGINT NOT NULL REFERENCES pets(id),
    message_id BIGINT REFERENCES messages(id) ON DELETE CASCADE,
    task_event_id BIGINT REFERENCES task_events(id) ON DELETE CASCADE,
    read_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK ((message_id IS NOT NULL) <> (task_event_id IS NOT NULL)),
    CHECK (recipient_pet_id <> actor_pet_id),
    UNIQUE (recipient_pet_id, message_id),
    UNIQUE (recipient_pet_id, task_event_id)
);

CREATE INDEX notifications_recipient_id_idx ON notifications(recipient_pet_id, id DESC);
