CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name VARCHAR(80) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE pets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL REFERENCES users(id),
    name VARCHAR(80) NOT NULL,
    species VARCHAR(80) NOT NULL,
    breed VARCHAR(80),
    gender VARCHAR(16) NOT NULL CHECK (gender IN ('MALE', 'FEMALE', 'UNKNOWN')),
    birthday DATE,
    bio VARCHAR(500),
    avatar_url VARCHAR(2048),
    private_profile BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX pets_owner_id_idx ON pets(owner_id);

CREATE TABLE communities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    description VARCHAR(500),
    rules VARCHAR(2000),
    created_by_pet_id BIGINT NOT NULL REFERENCES pets(id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX communities_name_unique_idx ON communities (LOWER(name));
CREATE INDEX communities_search_idx ON communities USING GIN (
    to_tsvector('english', name || ' ' || COALESCE(description, '') || ' ' || COALESCE(rules, ''))
);

CREATE TABLE community_members (
    community_id BIGINT NOT NULL REFERENCES communities(id) ON DELETE CASCADE,
    pet_id BIGINT NOT NULL REFERENCES pets(id) ON DELETE CASCADE,
    role VARCHAR(16) NOT NULL DEFAULT 'MEMBER' CHECK (role IN ('OWNER', 'MODERATOR', 'MEMBER')),
    joined_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (community_id, pet_id)
);

CREATE INDEX community_members_pet_idx ON community_members(pet_id, community_id);

CREATE TABLE posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id BIGINT NOT NULL REFERENCES pets(id),
    body VARCHAR(2000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX posts_created_at_id_idx ON posts(created_at DESC, id DESC);
CREATE INDEX posts_pet_created_at_id_idx ON posts(pet_id, created_at DESC, id DESC);

CREATE TABLE post_communities (
    post_id BIGINT PRIMARY KEY REFERENCES posts(id) ON DELETE CASCADE,
    community_id BIGINT NOT NULL REFERENCES communities(id)
);

CREATE INDEX post_communities_feed_idx ON post_communities(community_id, post_id);

CREATE TABLE post_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    url VARCHAR(2048) NOT NULL,
    sort_order INTEGER NOT NULL,
    UNIQUE (post_id, sort_order)
);

CREATE TABLE likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    pet_id BIGINT NOT NULL REFERENCES pets(id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (post_id, pet_id)
);

CREATE TABLE comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    pet_id BIGINT NOT NULL REFERENCES pets(id),
    body VARCHAR(500) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX comments_post_created_at_id_idx ON comments(post_id, created_at, id);

CREATE TABLE pet_follows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_pet_id BIGINT NOT NULL REFERENCES pets(id) ON DELETE CASCADE,
    following_pet_id BIGINT NOT NULL REFERENCES pets(id) ON DELETE CASCADE,
    accepted BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pet_follows_distinct_pets CHECK (follower_pet_id <> following_pet_id),
    CONSTRAINT pet_follows_unique_pair UNIQUE (follower_pet_id, following_pet_id)
);

CREATE INDEX pet_follows_following_idx ON pet_follows(following_pet_id, accepted, created_at DESC, id DESC);
CREATE INDEX pet_follows_follower_idx ON pet_follows(follower_pet_id, accepted, created_at DESC, id DESC);

CREATE TABLE pet_blocks (
    blocker_pet_id BIGINT NOT NULL REFERENCES pets(id) ON DELETE CASCADE,
    blocked_pet_id BIGINT NOT NULL REFERENCES pets(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (blocker_pet_id, blocked_pet_id),
    CONSTRAINT pet_blocks_distinct_pets CHECK (blocker_pet_id <> blocked_pet_id)
);

CREATE INDEX pet_blocks_blocked_idx ON pet_blocks(blocked_pet_id, blocker_pet_id);

CREATE TABLE pet_mutes (
    muter_pet_id BIGINT NOT NULL REFERENCES pets(id) ON DELETE CASCADE,
    muted_pet_id BIGINT NOT NULL REFERENCES pets(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (muter_pet_id, muted_pet_id),
    CONSTRAINT pet_mutes_distinct_pets CHECK (muter_pet_id <> muted_pet_id)
);

CREATE TABLE walks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id BIGINT NOT NULL REFERENCES pets(id),
    client_walk_id UUID NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ended_at TIMESTAMP WITH TIME ZONE NOT NULL,
    route geometry(LineString, 4326) NOT NULL CHECK (NOT ST_IsEmpty(route)),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT walks_valid_time CHECK (ended_at >= started_at),
    CONSTRAINT walks_pet_client_id_unique UNIQUE (pet_id, client_walk_id)
);

CREATE INDEX walks_pet_started_idx ON walks(pet_id, started_at DESC, id DESC);
CREATE INDEX walks_route_geography_idx ON walks USING GIST ((route::geography));

CREATE TABLE walk_points (
    walk_id BIGINT NOT NULL REFERENCES walks(id) ON DELETE CASCADE,
    sequence_number INTEGER NOT NULL CHECK (sequence_number >= 0),
    latitude DOUBLE PRECISION NOT NULL CHECK (latitude BETWEEN -90 AND 90),
    longitude DOUBLE PRECISION NOT NULL CHECK (longitude BETWEEN -180 AND 180),
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (walk_id, sequence_number)
);

CREATE TABLE territories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    walk_id BIGINT NOT NULL UNIQUE REFERENCES walks(id) ON DELETE CASCADE,
    area geometry(Polygon, 4326) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT territories_valid_area CHECK (ST_IsValid(area) AND NOT ST_IsEmpty(area))
);

CREATE INDEX territories_area_idx ON territories USING GIST (area);
