CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name VARCHAR(80) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE pets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL REFERENCES users(id),
    name VARCHAR(80) NOT NULL,
    species VARCHAR(80) NOT NULL,
    breed VARCHAR(80),
    gender VARCHAR(16) NOT NULL CHECK (gender IN ('MALE', 'FEMALE', 'UNKNOWN')),
    birthday DATE,
    bio VARCHAR(500),
    avatar_url VARCHAR(2048),
    private_profile BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX pets_owner_id_idx ON pets(owner_id);

CREATE TABLE posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id BIGINT NOT NULL REFERENCES pets(id),
    body VARCHAR(2000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX posts_created_at_id_idx ON posts(created_at DESC, id DESC);
CREATE INDEX posts_pet_created_at_id_idx ON posts(pet_id, created_at DESC, id DESC);

CREATE TABLE post_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    url VARCHAR(2048) NOT NULL,
    sort_order INTEGER NOT NULL,
    UNIQUE (post_id, sort_order)
);

CREATE TABLE likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    pet_id BIGINT NOT NULL REFERENCES pets(id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (post_id, pet_id)
);

CREATE TABLE comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    pet_id BIGINT NOT NULL REFERENCES pets(id),
    body VARCHAR(500) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX comments_post_created_at_id_idx ON comments(post_id, created_at, id);

CREATE TABLE pet_follows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_pet_id BIGINT NOT NULL REFERENCES pets(id) ON DELETE CASCADE,
    following_pet_id BIGINT NOT NULL REFERENCES pets(id) ON DELETE CASCADE,
    accepted BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pet_follows_distinct_pets CHECK (follower_pet_id <> following_pet_id),
    CONSTRAINT pet_follows_unique_pair UNIQUE (follower_pet_id, following_pet_id)
);

CREATE INDEX pet_follows_following_idx ON pet_follows(following_pet_id, accepted, created_at DESC, id DESC);
CREATE INDEX pet_follows_follower_idx ON pet_follows(follower_pet_id, accepted, created_at DESC, id DESC);

CREATE TABLE pet_blocks (
    blocker_pet_id BIGINT NOT NULL REFERENCES pets(id) ON DELETE CASCADE,
    blocked_pet_id BIGINT NOT NULL REFERENCES pets(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (blocker_pet_id, blocked_pet_id),
    CONSTRAINT pet_blocks_distinct_pets CHECK (blocker_pet_id <> blocked_pet_id)
);

CREATE INDEX pet_blocks_blocked_idx ON pet_blocks(blocked_pet_id, blocker_pet_id);

CREATE TABLE pet_mutes (
    muter_pet_id BIGINT NOT NULL REFERENCES pets(id) ON DELETE CASCADE,
    muted_pet_id BIGINT NOT NULL REFERENCES pets(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (muter_pet_id, muted_pet_id),
    CONSTRAINT pet_mutes_distinct_pets CHECK (muter_pet_id <> muted_pet_id)
);
