CREATE TABLE pet_follows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_pet_id BIGINT NOT NULL REFERENCES pets(id) ON DELETE CASCADE,
    following_pet_id BIGINT NOT NULL REFERENCES pets(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pet_follows_distinct_pets CHECK (follower_pet_id <> following_pet_id),
    CONSTRAINT pet_follows_unique_pair UNIQUE (follower_pet_id, following_pet_id)
);

CREATE INDEX pet_follows_following_idx ON pet_follows(following_pet_id, created_at DESC, id DESC);
CREATE INDEX pet_follows_follower_idx ON pet_follows(follower_pet_id, created_at DESC, id DESC);
